### ISSUE TITLE
Create Login and Signin API

### ISSUE THREAD

**Issue by tinkesh77** [tinkesh77/NovelNest#5]
Do all the validation.

test and make pull request.

**Comment by tinkesh77** [comment]
create sub module by clicking in main project folder you can image below for your reference.

![image](https://github.com/user-attachments/assets/b542aed1-ffca-40df-aaff-1073ab0d9744)

them create auth functionality,

**Comment by adpal2003** [comment]
ok

**Comment by tinkesh77** [comment]
# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://junction.proxy.rlwy.net:16718/railway
#mysql://root:KCCzTQSVFMGllqMChDRfCQmGqtUtWmIw@junction.proxy.rlwy.net:16718/railway
spring.datasource.username=root
spring.datasource.password=KCCzTQSVFMGllqMChDRfCQmGqtUtWmIw
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update


database configration
